#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPregunto.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EasyPregunto")]
	public partial class DataEasyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAprendiz(Aprendiz instance);
    partial void UpdateAprendiz(Aprendiz instance);
    partial void DeleteAprendiz(Aprendiz instance);
    partial void InsertArea_Conocimiento(Area_Conocimiento instance);
    partial void UpdateArea_Conocimiento(Area_Conocimiento instance);
    partial void DeleteArea_Conocimiento(Area_Conocimiento instance);
    partial void InsertCalificacion(Calificacion instance);
    partial void UpdateCalificacion(Calificacion instance);
    partial void DeleteCalificacion(Calificacion instance);
    partial void InsertEstado_Sesion(Estado_Sesion instance);
    partial void UpdateEstado_Sesion(Estado_Sesion instance);
    partial void DeleteEstado_Sesion(Estado_Sesion instance);
    partial void InsertEstados(Estados instance);
    partial void UpdateEstados(Estados instance);
    partial void DeleteEstados(Estados instance);
    partial void InsertExperiencia(Experiencia instance);
    partial void UpdateExperiencia(Experiencia instance);
    partial void DeleteExperiencia(Experiencia instance);
    partial void InsertFormacion_Academica(Formacion_Academica instance);
    partial void UpdateFormacion_Academica(Formacion_Academica instance);
    partial void DeleteFormacion_Academica(Formacion_Academica instance);
    partial void InsertNivel_Estudio(Nivel_Estudio instance);
    partial void UpdateNivel_Estudio(Nivel_Estudio instance);
    partial void DeleteNivel_Estudio(Nivel_Estudio instance);
    partial void InsertPregunta_Abierta(Pregunta_Abierta instance);
    partial void UpdatePregunta_Abierta(Pregunta_Abierta instance);
    partial void DeletePregunta_Abierta(Pregunta_Abierta instance);
    partial void InsertRol(Rol instance);
    partial void UpdateRol(Rol instance);
    partial void DeleteRol(Rol instance);
    partial void InsertSesion(Sesion instance);
    partial void UpdateSesion(Sesion instance);
    partial void DeleteSesion(Sesion instance);
    partial void InsertSub_area(Sub_area instance);
    partial void UpdateSub_area(Sub_area instance);
    partial void DeleteSub_area(Sub_area instance);
    partial void InsertTipo_Documento(Tipo_Documento instance);
    partial void UpdateTipo_Documento(Tipo_Documento instance);
    partial void DeleteTipo_Documento(Tipo_Documento instance);
    partial void InsertTitulo_Obtenido(Titulo_Obtenido instance);
    partial void UpdateTitulo_Obtenido(Titulo_Obtenido instance);
    partial void DeleteTitulo_Obtenido(Titulo_Obtenido instance);
    partial void InsertTutor(Tutor instance);
    partial void UpdateTutor(Tutor instance);
    partial void DeleteTutor(Tutor instance);
    #endregion
		
		public DataEasyDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EasyPreguntoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataEasyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEasyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEasyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEasyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Aprendiz> Aprendiz
		{
			get
			{
				return this.GetTable<Aprendiz>();
			}
		}
		
		public System.Data.Linq.Table<Area_Conocimiento> Area_Conocimiento
		{
			get
			{
				return this.GetTable<Area_Conocimiento>();
			}
		}
		
		public System.Data.Linq.Table<Calificacion> Calificacion
		{
			get
			{
				return this.GetTable<Calificacion>();
			}
		}
		
		public System.Data.Linq.Table<Estado_Sesion> Estado_Sesion
		{
			get
			{
				return this.GetTable<Estado_Sesion>();
			}
		}
		
		public System.Data.Linq.Table<Estados> Estados
		{
			get
			{
				return this.GetTable<Estados>();
			}
		}
		
		public System.Data.Linq.Table<Experiencia> Experiencia
		{
			get
			{
				return this.GetTable<Experiencia>();
			}
		}
		
		public System.Data.Linq.Table<Formacion_Academica> Formacion_Academica
		{
			get
			{
				return this.GetTable<Formacion_Academica>();
			}
		}
		
		public System.Data.Linq.Table<Nivel_Estudio> Nivel_Estudio
		{
			get
			{
				return this.GetTable<Nivel_Estudio>();
			}
		}
		
		public System.Data.Linq.Table<Nivel_estudio_Has_Tutor> Nivel_estudio_Has_Tutor
		{
			get
			{
				return this.GetTable<Nivel_estudio_Has_Tutor>();
			}
		}
		
		public System.Data.Linq.Table<Pregunta_Abierta> Pregunta_Abierta
		{
			get
			{
				return this.GetTable<Pregunta_Abierta>();
			}
		}
		
		public System.Data.Linq.Table<Rol> Rol
		{
			get
			{
				return this.GetTable<Rol>();
			}
		}
		
		public System.Data.Linq.Table<Sesion> Sesion
		{
			get
			{
				return this.GetTable<Sesion>();
			}
		}
		
		public System.Data.Linq.Table<Sub_area> Sub_area
		{
			get
			{
				return this.GetTable<Sub_area>();
			}
		}
		
		public System.Data.Linq.Table<Tipo_Documento> Tipo_Documento
		{
			get
			{
				return this.GetTable<Tipo_Documento>();
			}
		}
		
		public System.Data.Linq.Table<Titulo_Obtenido> Titulo_Obtenido
		{
			get
			{
				return this.GetTable<Titulo_Obtenido>();
			}
		}
		
		public System.Data.Linq.Table<Tutor> Tutor
		{
			get
			{
				return this.GetTable<Tutor>();
			}
		}
		
		public System.Data.Linq.Table<Tutor_Has_Area_Conocimiento> Tutor_Has_Area_Conocimiento
		{
			get
			{
				return this.GetTable<Tutor_Has_Area_Conocimiento>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tutodisponible3")]
		public ISingleResult<tutodisponible3Result> tutodisponible3([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="Int")] System.Nullable<int> estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Materia", DbType="Int")] System.Nullable<int> materia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), estado, materia);
			return ((ISingleResult<tutodisponible3Result>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Aprendiz")]
	public partial class Aprendiz : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_aprendiz;
		
		private string _Nombre_aprendiz;
		
		private string _Apellidos_aprendiz;
		
		private string _Correo_Electronico_aprendiz;
		
		private string _Clave_aprendiz;
		
		private string _Alias_aprendiz;
		
		private int _Rol;
		
		private EntitySet<Estado_Sesion> _Estado_Sesion;
		
		private EntityRef<Rol> _Rol1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_aprendizChanging(int value);
    partial void OnId_aprendizChanged();
    partial void OnNombre_aprendizChanging(string value);
    partial void OnNombre_aprendizChanged();
    partial void OnApellidos_aprendizChanging(string value);
    partial void OnApellidos_aprendizChanged();
    partial void OnCorreo_Electronico_aprendizChanging(string value);
    partial void OnCorreo_Electronico_aprendizChanged();
    partial void OnClave_aprendizChanging(string value);
    partial void OnClave_aprendizChanged();
    partial void OnAlias_aprendizChanging(string value);
    partial void OnAlias_aprendizChanged();
    partial void OnRolChanging(int value);
    partial void OnRolChanged();
    #endregion
		
		public Aprendiz()
		{
			this._Estado_Sesion = new EntitySet<Estado_Sesion>(new Action<Estado_Sesion>(this.attach_Estado_Sesion), new Action<Estado_Sesion>(this.detach_Estado_Sesion));
			this._Rol1 = default(EntityRef<Rol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_aprendiz", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_aprendiz
		{
			get
			{
				return this._Id_aprendiz;
			}
			set
			{
				if ((this._Id_aprendiz != value))
				{
					this.OnId_aprendizChanging(value);
					this.SendPropertyChanging();
					this._Id_aprendiz = value;
					this.SendPropertyChanged("Id_aprendiz");
					this.OnId_aprendizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_aprendiz", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre_aprendiz
		{
			get
			{
				return this._Nombre_aprendiz;
			}
			set
			{
				if ((this._Nombre_aprendiz != value))
				{
					this.OnNombre_aprendizChanging(value);
					this.SendPropertyChanging();
					this._Nombre_aprendiz = value;
					this.SendPropertyChanged("Nombre_aprendiz");
					this.OnNombre_aprendizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos_aprendiz", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Apellidos_aprendiz
		{
			get
			{
				return this._Apellidos_aprendiz;
			}
			set
			{
				if ((this._Apellidos_aprendiz != value))
				{
					this.OnApellidos_aprendizChanging(value);
					this.SendPropertyChanging();
					this._Apellidos_aprendiz = value;
					this.SendPropertyChanged("Apellidos_aprendiz");
					this.OnApellidos_aprendizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo_Electronico_aprendiz", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Correo_Electronico_aprendiz
		{
			get
			{
				return this._Correo_Electronico_aprendiz;
			}
			set
			{
				if ((this._Correo_Electronico_aprendiz != value))
				{
					this.OnCorreo_Electronico_aprendizChanging(value);
					this.SendPropertyChanging();
					this._Correo_Electronico_aprendiz = value;
					this.SendPropertyChanged("Correo_Electronico_aprendiz");
					this.OnCorreo_Electronico_aprendizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave_aprendiz", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Clave_aprendiz
		{
			get
			{
				return this._Clave_aprendiz;
			}
			set
			{
				if ((this._Clave_aprendiz != value))
				{
					this.OnClave_aprendizChanging(value);
					this.SendPropertyChanging();
					this._Clave_aprendiz = value;
					this.SendPropertyChanged("Clave_aprendiz");
					this.OnClave_aprendizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alias_aprendiz", DbType="VarChar(30)")]
		public string Alias_aprendiz
		{
			get
			{
				return this._Alias_aprendiz;
			}
			set
			{
				if ((this._Alias_aprendiz != value))
				{
					this.OnAlias_aprendizChanging(value);
					this.SendPropertyChanging();
					this._Alias_aprendiz = value;
					this.SendPropertyChanged("Alias_aprendiz");
					this.OnAlias_aprendizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="Int NOT NULL")]
		public int Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					if (this._Rol1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRolChanging(value);
					this.SendPropertyChanging();
					this._Rol = value;
					this.SendPropertyChanged("Rol");
					this.OnRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aprendiz_Estado_Sesion", Storage="_Estado_Sesion", ThisKey="Id_aprendiz", OtherKey="Aprendiz")]
		public EntitySet<Estado_Sesion> Estado_Sesion
		{
			get
			{
				return this._Estado_Sesion;
			}
			set
			{
				this._Estado_Sesion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_Aprendiz", Storage="_Rol1", ThisKey="Rol", OtherKey="Id_Rol", IsForeignKey=true)]
		public Rol Rol1
		{
			get
			{
				return this._Rol1.Entity;
			}
			set
			{
				Rol previousValue = this._Rol1.Entity;
				if (((previousValue != value) 
							|| (this._Rol1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rol1.Entity = null;
						previousValue.Aprendiz.Remove(this);
					}
					this._Rol1.Entity = value;
					if ((value != null))
					{
						value.Aprendiz.Add(this);
						this._Rol = value.Id_Rol;
					}
					else
					{
						this._Rol = default(int);
					}
					this.SendPropertyChanged("Rol1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Estado_Sesion(Estado_Sesion entity)
		{
			this.SendPropertyChanging();
			entity.Aprendiz1 = this;
		}
		
		private void detach_Estado_Sesion(Estado_Sesion entity)
		{
			this.SendPropertyChanging();
			entity.Aprendiz1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Area_Conocimiento")]
	public partial class Area_Conocimiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Area;
		
		private string _Nombre_Area;
		
		private EntitySet<Estado_Sesion> _Estado_Sesion;
		
		private EntitySet<Pregunta_Abierta> _Pregunta_Abierta;
		
		private EntitySet<Sub_area> _Sub_area;
		
		private EntitySet<Tutor> _Tutor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_AreaChanging(int value);
    partial void OnId_AreaChanged();
    partial void OnNombre_AreaChanging(string value);
    partial void OnNombre_AreaChanged();
    #endregion
		
		public Area_Conocimiento()
		{
			this._Estado_Sesion = new EntitySet<Estado_Sesion>(new Action<Estado_Sesion>(this.attach_Estado_Sesion), new Action<Estado_Sesion>(this.detach_Estado_Sesion));
			this._Pregunta_Abierta = new EntitySet<Pregunta_Abierta>(new Action<Pregunta_Abierta>(this.attach_Pregunta_Abierta), new Action<Pregunta_Abierta>(this.detach_Pregunta_Abierta));
			this._Sub_area = new EntitySet<Sub_area>(new Action<Sub_area>(this.attach_Sub_area), new Action<Sub_area>(this.detach_Sub_area));
			this._Tutor = new EntitySet<Tutor>(new Action<Tutor>(this.attach_Tutor), new Action<Tutor>(this.detach_Tutor));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Area", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Area
		{
			get
			{
				return this._Id_Area;
			}
			set
			{
				if ((this._Id_Area != value))
				{
					this.OnId_AreaChanging(value);
					this.SendPropertyChanging();
					this._Id_Area = value;
					this.SendPropertyChanged("Id_Area");
					this.OnId_AreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Area", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre_Area
		{
			get
			{
				return this._Nombre_Area;
			}
			set
			{
				if ((this._Nombre_Area != value))
				{
					this.OnNombre_AreaChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Area = value;
					this.SendPropertyChanged("Nombre_Area");
					this.OnNombre_AreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Area_Conocimiento_Estado_Sesion", Storage="_Estado_Sesion", ThisKey="Id_Area", OtherKey="IdArea")]
		public EntitySet<Estado_Sesion> Estado_Sesion
		{
			get
			{
				return this._Estado_Sesion;
			}
			set
			{
				this._Estado_Sesion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Area_Conocimiento_Pregunta_Abierta", Storage="_Pregunta_Abierta", ThisKey="Id_Area", OtherKey="Area")]
		public EntitySet<Pregunta_Abierta> Pregunta_Abierta
		{
			get
			{
				return this._Pregunta_Abierta;
			}
			set
			{
				this._Pregunta_Abierta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Area_Conocimiento_Sub_area", Storage="_Sub_area", ThisKey="Id_Area", OtherKey="Area")]
		public EntitySet<Sub_area> Sub_area
		{
			get
			{
				return this._Sub_area;
			}
			set
			{
				this._Sub_area.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Area_Conocimiento_Tutor", Storage="_Tutor", ThisKey="Id_Area", OtherKey="Area_Conocimiento")]
		public EntitySet<Tutor> Tutor
		{
			get
			{
				return this._Tutor;
			}
			set
			{
				this._Tutor.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Estado_Sesion(Estado_Sesion entity)
		{
			this.SendPropertyChanging();
			entity.Area_Conocimiento = this;
		}
		
		private void detach_Estado_Sesion(Estado_Sesion entity)
		{
			this.SendPropertyChanging();
			entity.Area_Conocimiento = null;
		}
		
		private void attach_Pregunta_Abierta(Pregunta_Abierta entity)
		{
			this.SendPropertyChanging();
			entity.Area_Conocimiento = this;
		}
		
		private void detach_Pregunta_Abierta(Pregunta_Abierta entity)
		{
			this.SendPropertyChanging();
			entity.Area_Conocimiento = null;
		}
		
		private void attach_Sub_area(Sub_area entity)
		{
			this.SendPropertyChanging();
			entity.Area_Conocimiento = this;
		}
		
		private void detach_Sub_area(Sub_area entity)
		{
			this.SendPropertyChanging();
			entity.Area_Conocimiento = null;
		}
		
		private void attach_Tutor(Tutor entity)
		{
			this.SendPropertyChanging();
			entity.Area_Conocimiento1 = this;
		}
		
		private void detach_Tutor(Tutor entity)
		{
			this.SendPropertyChanging();
			entity.Area_Conocimiento1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Calificacion")]
	public partial class Calificacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Calificacion;
		
		private string _Descripcion_Calificacion;
		
		private EntitySet<Sesion> _Sesion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_CalificacionChanging(int value);
    partial void OnId_CalificacionChanged();
    partial void OnDescripcion_CalificacionChanging(string value);
    partial void OnDescripcion_CalificacionChanged();
    #endregion
		
		public Calificacion()
		{
			this._Sesion = new EntitySet<Sesion>(new Action<Sesion>(this.attach_Sesion), new Action<Sesion>(this.detach_Sesion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Calificacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Calificacion
		{
			get
			{
				return this._Id_Calificacion;
			}
			set
			{
				if ((this._Id_Calificacion != value))
				{
					this.OnId_CalificacionChanging(value);
					this.SendPropertyChanging();
					this._Id_Calificacion = value;
					this.SendPropertyChanged("Id_Calificacion");
					this.OnId_CalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion_Calificacion", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Descripcion_Calificacion
		{
			get
			{
				return this._Descripcion_Calificacion;
			}
			set
			{
				if ((this._Descripcion_Calificacion != value))
				{
					this.OnDescripcion_CalificacionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion_Calificacion = value;
					this.SendPropertyChanged("Descripcion_Calificacion");
					this.OnDescripcion_CalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Calificacion_Sesion", Storage="_Sesion", ThisKey="Id_Calificacion", OtherKey="Calificacion")]
		public EntitySet<Sesion> Sesion
		{
			get
			{
				return this._Sesion;
			}
			set
			{
				this._Sesion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sesion(Sesion entity)
		{
			this.SendPropertyChanging();
			entity.Calificacion1 = this;
		}
		
		private void detach_Sesion(Sesion entity)
		{
			this.SendPropertyChanging();
			entity.Calificacion1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estado_Sesion")]
	public partial class Estado_Sesion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Estado_Sesion;
		
		private string _Estado;
		
		private int _Aprendiz;
		
		private System.Nullable<int> _Tutor;
		
		private int _IdArea;
		
		private EntitySet<Sesion> _Sesion;
		
		private EntityRef<Aprendiz> _Aprendiz1;
		
		private EntityRef<Area_Conocimiento> _Area_Conocimiento;
		
		private EntityRef<Tutor> _Tutor1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_Estado_SesionChanging(int value);
    partial void OnId_Estado_SesionChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnAprendizChanging(int value);
    partial void OnAprendizChanged();
    partial void OnTutorChanging(System.Nullable<int> value);
    partial void OnTutorChanged();
    partial void OnIdAreaChanging(int value);
    partial void OnIdAreaChanged();
    #endregion
		
		public Estado_Sesion()
		{
			this._Sesion = new EntitySet<Sesion>(new Action<Sesion>(this.attach_Sesion), new Action<Sesion>(this.detach_Sesion));
			this._Aprendiz1 = default(EntityRef<Aprendiz>);
			this._Area_Conocimiento = default(EntityRef<Area_Conocimiento>);
			this._Tutor1 = default(EntityRef<Tutor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Estado_Sesion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Estado_Sesion
		{
			get
			{
				return this._Id_Estado_Sesion;
			}
			set
			{
				if ((this._Id_Estado_Sesion != value))
				{
					this.OnId_Estado_SesionChanging(value);
					this.SendPropertyChanging();
					this._Id_Estado_Sesion = value;
					this.SendPropertyChanged("Id_Estado_Sesion");
					this.OnId_Estado_SesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprendiz", DbType="Int NOT NULL")]
		public int Aprendiz
		{
			get
			{
				return this._Aprendiz;
			}
			set
			{
				if ((this._Aprendiz != value))
				{
					if (this._Aprendiz1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAprendizChanging(value);
					this.SendPropertyChanging();
					this._Aprendiz = value;
					this.SendPropertyChanged("Aprendiz");
					this.OnAprendizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutor", DbType="Int")]
		public System.Nullable<int> Tutor
		{
			get
			{
				return this._Tutor;
			}
			set
			{
				if ((this._Tutor != value))
				{
					if (this._Tutor1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTutorChanging(value);
					this.SendPropertyChanging();
					this._Tutor = value;
					this.SendPropertyChanged("Tutor");
					this.OnTutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArea", DbType="Int NOT NULL")]
		public int IdArea
		{
			get
			{
				return this._IdArea;
			}
			set
			{
				if ((this._IdArea != value))
				{
					if (this._Area_Conocimiento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAreaChanging(value);
					this.SendPropertyChanging();
					this._IdArea = value;
					this.SendPropertyChanged("IdArea");
					this.OnIdAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Sesion_Sesion", Storage="_Sesion", ThisKey="Id_Estado_Sesion", OtherKey="Estado_Sesion")]
		public EntitySet<Sesion> Sesion
		{
			get
			{
				return this._Sesion;
			}
			set
			{
				this._Sesion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aprendiz_Estado_Sesion", Storage="_Aprendiz1", ThisKey="Aprendiz", OtherKey="Id_aprendiz", IsForeignKey=true)]
		public Aprendiz Aprendiz1
		{
			get
			{
				return this._Aprendiz1.Entity;
			}
			set
			{
				Aprendiz previousValue = this._Aprendiz1.Entity;
				if (((previousValue != value) 
							|| (this._Aprendiz1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Aprendiz1.Entity = null;
						previousValue.Estado_Sesion.Remove(this);
					}
					this._Aprendiz1.Entity = value;
					if ((value != null))
					{
						value.Estado_Sesion.Add(this);
						this._Aprendiz = value.Id_aprendiz;
					}
					else
					{
						this._Aprendiz = default(int);
					}
					this.SendPropertyChanged("Aprendiz1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Area_Conocimiento_Estado_Sesion", Storage="_Area_Conocimiento", ThisKey="IdArea", OtherKey="Id_Area", IsForeignKey=true)]
		public Area_Conocimiento Area_Conocimiento
		{
			get
			{
				return this._Area_Conocimiento.Entity;
			}
			set
			{
				Area_Conocimiento previousValue = this._Area_Conocimiento.Entity;
				if (((previousValue != value) 
							|| (this._Area_Conocimiento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Area_Conocimiento.Entity = null;
						previousValue.Estado_Sesion.Remove(this);
					}
					this._Area_Conocimiento.Entity = value;
					if ((value != null))
					{
						value.Estado_Sesion.Add(this);
						this._IdArea = value.Id_Area;
					}
					else
					{
						this._IdArea = default(int);
					}
					this.SendPropertyChanged("Area_Conocimiento");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tutor_Estado_Sesion", Storage="_Tutor1", ThisKey="Tutor", OtherKey="Id_Tutor", IsForeignKey=true)]
		public Tutor Tutor1
		{
			get
			{
				return this._Tutor1.Entity;
			}
			set
			{
				Tutor previousValue = this._Tutor1.Entity;
				if (((previousValue != value) 
							|| (this._Tutor1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tutor1.Entity = null;
						previousValue.Estado_Sesion.Remove(this);
					}
					this._Tutor1.Entity = value;
					if ((value != null))
					{
						value.Estado_Sesion.Add(this);
						this._Tutor = value.Id_Tutor;
					}
					else
					{
						this._Tutor = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tutor1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sesion(Sesion entity)
		{
			this.SendPropertyChanging();
			entity.Estado_Sesion1 = this;
		}
		
		private void detach_Sesion(Sesion entity)
		{
			this.SendPropertyChanging();
			entity.Estado_Sesion1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estados")]
	public partial class Estados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_sesion_tutor;
		
		private string _Estado_tutor;
		
		private EntitySet<Tutor> _Tutor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_sesion_tutorChanging(int value);
    partial void OnId_sesion_tutorChanged();
    partial void OnEstado_tutorChanging(string value);
    partial void OnEstado_tutorChanged();
    #endregion
		
		public Estados()
		{
			this._Tutor = new EntitySet<Tutor>(new Action<Tutor>(this.attach_Tutor), new Action<Tutor>(this.detach_Tutor));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_sesion_tutor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_sesion_tutor
		{
			get
			{
				return this._Id_sesion_tutor;
			}
			set
			{
				if ((this._Id_sesion_tutor != value))
				{
					this.OnId_sesion_tutorChanging(value);
					this.SendPropertyChanging();
					this._Id_sesion_tutor = value;
					this.SendPropertyChanged("Id_sesion_tutor");
					this.OnId_sesion_tutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_tutor", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Estado_tutor
		{
			get
			{
				return this._Estado_tutor;
			}
			set
			{
				if ((this._Estado_tutor != value))
				{
					this.OnEstado_tutorChanging(value);
					this.SendPropertyChanging();
					this._Estado_tutor = value;
					this.SendPropertyChanged("Estado_tutor");
					this.OnEstado_tutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estados_Tutor", Storage="_Tutor", ThisKey="Id_sesion_tutor", OtherKey="Estado")]
		public EntitySet<Tutor> Tutor
		{
			get
			{
				return this._Tutor;
			}
			set
			{
				this._Tutor.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tutor(Tutor entity)
		{
			this.SendPropertyChanging();
			entity.Estados = this;
		}
		
		private void detach_Tutor(Tutor entity)
		{
			this.SendPropertyChanging();
			entity.Estados = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Experiencia")]
	public partial class Experiencia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Experiencia;
		
		private string _EmpresaInstitucion_Experiencia;
		
		private string _Cargo_Experiencia;
		
		private System.DateTime _FechaIngreso_Experiencia;
		
		private System.DateTime _FechaSalida_Experiencia;
		
		private string _MotivoRetiro_Experiencia;
		
		private EntitySet<Tutor> _Tutor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_ExperienciaChanging(int value);
    partial void OnId_ExperienciaChanged();
    partial void OnEmpresaInstitucion_ExperienciaChanging(string value);
    partial void OnEmpresaInstitucion_ExperienciaChanged();
    partial void OnCargo_ExperienciaChanging(string value);
    partial void OnCargo_ExperienciaChanged();
    partial void OnFechaIngreso_ExperienciaChanging(System.DateTime value);
    partial void OnFechaIngreso_ExperienciaChanged();
    partial void OnFechaSalida_ExperienciaChanging(System.DateTime value);
    partial void OnFechaSalida_ExperienciaChanged();
    partial void OnMotivoRetiro_ExperienciaChanging(string value);
    partial void OnMotivoRetiro_ExperienciaChanged();
    #endregion
		
		public Experiencia()
		{
			this._Tutor = new EntitySet<Tutor>(new Action<Tutor>(this.attach_Tutor), new Action<Tutor>(this.detach_Tutor));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Experiencia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Experiencia
		{
			get
			{
				return this._Id_Experiencia;
			}
			set
			{
				if ((this._Id_Experiencia != value))
				{
					this.OnId_ExperienciaChanging(value);
					this.SendPropertyChanging();
					this._Id_Experiencia = value;
					this.SendPropertyChanged("Id_Experiencia");
					this.OnId_ExperienciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpresaInstitucion_Experiencia", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string EmpresaInstitucion_Experiencia
		{
			get
			{
				return this._EmpresaInstitucion_Experiencia;
			}
			set
			{
				if ((this._EmpresaInstitucion_Experiencia != value))
				{
					this.OnEmpresaInstitucion_ExperienciaChanging(value);
					this.SendPropertyChanging();
					this._EmpresaInstitucion_Experiencia = value;
					this.SendPropertyChanged("EmpresaInstitucion_Experiencia");
					this.OnEmpresaInstitucion_ExperienciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo_Experiencia", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Cargo_Experiencia
		{
			get
			{
				return this._Cargo_Experiencia;
			}
			set
			{
				if ((this._Cargo_Experiencia != value))
				{
					this.OnCargo_ExperienciaChanging(value);
					this.SendPropertyChanging();
					this._Cargo_Experiencia = value;
					this.SendPropertyChanged("Cargo_Experiencia");
					this.OnCargo_ExperienciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaIngreso_Experiencia", DbType="Date NOT NULL")]
		public System.DateTime FechaIngreso_Experiencia
		{
			get
			{
				return this._FechaIngreso_Experiencia;
			}
			set
			{
				if ((this._FechaIngreso_Experiencia != value))
				{
					this.OnFechaIngreso_ExperienciaChanging(value);
					this.SendPropertyChanging();
					this._FechaIngreso_Experiencia = value;
					this.SendPropertyChanged("FechaIngreso_Experiencia");
					this.OnFechaIngreso_ExperienciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSalida_Experiencia", DbType="Date NOT NULL")]
		public System.DateTime FechaSalida_Experiencia
		{
			get
			{
				return this._FechaSalida_Experiencia;
			}
			set
			{
				if ((this._FechaSalida_Experiencia != value))
				{
					this.OnFechaSalida_ExperienciaChanging(value);
					this.SendPropertyChanging();
					this._FechaSalida_Experiencia = value;
					this.SendPropertyChanged("FechaSalida_Experiencia");
					this.OnFechaSalida_ExperienciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotivoRetiro_Experiencia", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MotivoRetiro_Experiencia
		{
			get
			{
				return this._MotivoRetiro_Experiencia;
			}
			set
			{
				if ((this._MotivoRetiro_Experiencia != value))
				{
					this.OnMotivoRetiro_ExperienciaChanging(value);
					this.SendPropertyChanging();
					this._MotivoRetiro_Experiencia = value;
					this.SendPropertyChanged("MotivoRetiro_Experiencia");
					this.OnMotivoRetiro_ExperienciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Experiencia_Tutor", Storage="_Tutor", ThisKey="Id_Experiencia", OtherKey="Experiencia")]
		public EntitySet<Tutor> Tutor
		{
			get
			{
				return this._Tutor;
			}
			set
			{
				this._Tutor.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tutor(Tutor entity)
		{
			this.SendPropertyChanging();
			entity.Experiencia1 = this;
		}
		
		private void detach_Tutor(Tutor entity)
		{
			this.SendPropertyChanging();
			entity.Experiencia1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Formacion_Academica")]
	public partial class Formacion_Academica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Formacion;
		
		private string _Nivel_Formacion;
		
		private EntitySet<Nivel_Estudio> _Nivel_Estudio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_FormacionChanging(int value);
    partial void OnId_FormacionChanged();
    partial void OnNivel_FormacionChanging(string value);
    partial void OnNivel_FormacionChanged();
    #endregion
		
		public Formacion_Academica()
		{
			this._Nivel_Estudio = new EntitySet<Nivel_Estudio>(new Action<Nivel_Estudio>(this.attach_Nivel_Estudio), new Action<Nivel_Estudio>(this.detach_Nivel_Estudio));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Formacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Formacion
		{
			get
			{
				return this._Id_Formacion;
			}
			set
			{
				if ((this._Id_Formacion != value))
				{
					this.OnId_FormacionChanging(value);
					this.SendPropertyChanging();
					this._Id_Formacion = value;
					this.SendPropertyChanged("Id_Formacion");
					this.OnId_FormacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel_Formacion", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nivel_Formacion
		{
			get
			{
				return this._Nivel_Formacion;
			}
			set
			{
				if ((this._Nivel_Formacion != value))
				{
					this.OnNivel_FormacionChanging(value);
					this.SendPropertyChanging();
					this._Nivel_Formacion = value;
					this.SendPropertyChanged("Nivel_Formacion");
					this.OnNivel_FormacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Formacion_Academica_Nivel_Estudio", Storage="_Nivel_Estudio", ThisKey="Id_Formacion", OtherKey="Formacion_Academica")]
		public EntitySet<Nivel_Estudio> Nivel_Estudio
		{
			get
			{
				return this._Nivel_Estudio;
			}
			set
			{
				this._Nivel_Estudio.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Nivel_Estudio(Nivel_Estudio entity)
		{
			this.SendPropertyChanging();
			entity.Formacion_Academica1 = this;
		}
		
		private void detach_Nivel_Estudio(Nivel_Estudio entity)
		{
			this.SendPropertyChanging();
			entity.Formacion_Academica1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nivel_Estudio")]
	public partial class Nivel_Estudio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdNivel_Estudio;
		
		private int _Formacion_Academica;
		
		private int _Titulo_Obtenido;
		
		private string _Institucion_Estudio;
		
		private string _AnioFinalizacion_Estudio;
		
		private EntityRef<Formacion_Academica> _Formacion_Academica1;
		
		private EntityRef<Titulo_Obtenido> _Titulo_Obtenido1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdNivel_EstudioChanging(int value);
    partial void OnIdNivel_EstudioChanged();
    partial void OnFormacion_AcademicaChanging(int value);
    partial void OnFormacion_AcademicaChanged();
    partial void OnTitulo_ObtenidoChanging(int value);
    partial void OnTitulo_ObtenidoChanged();
    partial void OnInstitucion_EstudioChanging(string value);
    partial void OnInstitucion_EstudioChanged();
    partial void OnAnioFinalizacion_EstudioChanging(string value);
    partial void OnAnioFinalizacion_EstudioChanged();
    #endregion
		
		public Nivel_Estudio()
		{
			this._Formacion_Academica1 = default(EntityRef<Formacion_Academica>);
			this._Titulo_Obtenido1 = default(EntityRef<Titulo_Obtenido>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNivel_Estudio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdNivel_Estudio
		{
			get
			{
				return this._IdNivel_Estudio;
			}
			set
			{
				if ((this._IdNivel_Estudio != value))
				{
					this.OnIdNivel_EstudioChanging(value);
					this.SendPropertyChanging();
					this._IdNivel_Estudio = value;
					this.SendPropertyChanged("IdNivel_Estudio");
					this.OnIdNivel_EstudioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Formacion_Academica", DbType="Int NOT NULL")]
		public int Formacion_Academica
		{
			get
			{
				return this._Formacion_Academica;
			}
			set
			{
				if ((this._Formacion_Academica != value))
				{
					if (this._Formacion_Academica1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFormacion_AcademicaChanging(value);
					this.SendPropertyChanging();
					this._Formacion_Academica = value;
					this.SendPropertyChanged("Formacion_Academica");
					this.OnFormacion_AcademicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo_Obtenido", DbType="Int NOT NULL")]
		public int Titulo_Obtenido
		{
			get
			{
				return this._Titulo_Obtenido;
			}
			set
			{
				if ((this._Titulo_Obtenido != value))
				{
					if (this._Titulo_Obtenido1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTitulo_ObtenidoChanging(value);
					this.SendPropertyChanging();
					this._Titulo_Obtenido = value;
					this.SendPropertyChanged("Titulo_Obtenido");
					this.OnTitulo_ObtenidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Institucion_Estudio", DbType="VarChar(100)")]
		public string Institucion_Estudio
		{
			get
			{
				return this._Institucion_Estudio;
			}
			set
			{
				if ((this._Institucion_Estudio != value))
				{
					this.OnInstitucion_EstudioChanging(value);
					this.SendPropertyChanging();
					this._Institucion_Estudio = value;
					this.SendPropertyChanged("Institucion_Estudio");
					this.OnInstitucion_EstudioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnioFinalizacion_Estudio", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string AnioFinalizacion_Estudio
		{
			get
			{
				return this._AnioFinalizacion_Estudio;
			}
			set
			{
				if ((this._AnioFinalizacion_Estudio != value))
				{
					this.OnAnioFinalizacion_EstudioChanging(value);
					this.SendPropertyChanging();
					this._AnioFinalizacion_Estudio = value;
					this.SendPropertyChanged("AnioFinalizacion_Estudio");
					this.OnAnioFinalizacion_EstudioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Formacion_Academica_Nivel_Estudio", Storage="_Formacion_Academica1", ThisKey="Formacion_Academica", OtherKey="Id_Formacion", IsForeignKey=true)]
		public Formacion_Academica Formacion_Academica1
		{
			get
			{
				return this._Formacion_Academica1.Entity;
			}
			set
			{
				Formacion_Academica previousValue = this._Formacion_Academica1.Entity;
				if (((previousValue != value) 
							|| (this._Formacion_Academica1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Formacion_Academica1.Entity = null;
						previousValue.Nivel_Estudio.Remove(this);
					}
					this._Formacion_Academica1.Entity = value;
					if ((value != null))
					{
						value.Nivel_Estudio.Add(this);
						this._Formacion_Academica = value.Id_Formacion;
					}
					else
					{
						this._Formacion_Academica = default(int);
					}
					this.SendPropertyChanged("Formacion_Academica1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Titulo_Obtenido_Nivel_Estudio", Storage="_Titulo_Obtenido1", ThisKey="Titulo_Obtenido", OtherKey="Id_Titulo", IsForeignKey=true)]
		public Titulo_Obtenido Titulo_Obtenido1
		{
			get
			{
				return this._Titulo_Obtenido1.Entity;
			}
			set
			{
				Titulo_Obtenido previousValue = this._Titulo_Obtenido1.Entity;
				if (((previousValue != value) 
							|| (this._Titulo_Obtenido1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Titulo_Obtenido1.Entity = null;
						previousValue.Nivel_Estudio.Remove(this);
					}
					this._Titulo_Obtenido1.Entity = value;
					if ((value != null))
					{
						value.Nivel_Estudio.Add(this);
						this._Titulo_Obtenido = value.Id_Titulo;
					}
					else
					{
						this._Titulo_Obtenido = default(int);
					}
					this.SendPropertyChanged("Titulo_Obtenido1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nivel_estudio_Has_Tutor")]
	public partial class Nivel_estudio_Has_Tutor
	{
		
		private int _Nivel_Estudio;
		
		private int _Tutor;
		
		public Nivel_estudio_Has_Tutor()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel_Estudio", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Nivel_Estudio
		{
			get
			{
				return this._Nivel_Estudio;
			}
			set
			{
				if ((this._Nivel_Estudio != value))
				{
					this._Nivel_Estudio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutor", DbType="Int NOT NULL")]
		public int Tutor
		{
			get
			{
				return this._Tutor;
			}
			set
			{
				if ((this._Tutor != value))
				{
					this._Tutor = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pregunta_Abierta")]
	public partial class Pregunta_Abierta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Pregunta_Abierta;
		
		private string _Pregunta;
		
		private int _Area;
		
		private EntityRef<Area_Conocimiento> _Area_Conocimiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_Pregunta_AbiertaChanging(int value);
    partial void OnId_Pregunta_AbiertaChanged();
    partial void OnPreguntaChanging(string value);
    partial void OnPreguntaChanged();
    partial void OnAreaChanging(int value);
    partial void OnAreaChanged();
    #endregion
		
		public Pregunta_Abierta()
		{
			this._Area_Conocimiento = default(EntityRef<Area_Conocimiento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Pregunta_Abierta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Pregunta_Abierta
		{
			get
			{
				return this._Id_Pregunta_Abierta;
			}
			set
			{
				if ((this._Id_Pregunta_Abierta != value))
				{
					this.OnId_Pregunta_AbiertaChanging(value);
					this.SendPropertyChanging();
					this._Id_Pregunta_Abierta = value;
					this.SendPropertyChanged("Id_Pregunta_Abierta");
					this.OnId_Pregunta_AbiertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pregunta", DbType="VarChar(250)")]
		public string Pregunta
		{
			get
			{
				return this._Pregunta;
			}
			set
			{
				if ((this._Pregunta != value))
				{
					this.OnPreguntaChanging(value);
					this.SendPropertyChanging();
					this._Pregunta = value;
					this.SendPropertyChanged("Pregunta");
					this.OnPreguntaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="Int NOT NULL")]
		public int Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					if (this._Area_Conocimiento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAreaChanging(value);
					this.SendPropertyChanging();
					this._Area = value;
					this.SendPropertyChanged("Area");
					this.OnAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Area_Conocimiento_Pregunta_Abierta", Storage="_Area_Conocimiento", ThisKey="Area", OtherKey="Id_Area", IsForeignKey=true)]
		public Area_Conocimiento Area_Conocimiento
		{
			get
			{
				return this._Area_Conocimiento.Entity;
			}
			set
			{
				Area_Conocimiento previousValue = this._Area_Conocimiento.Entity;
				if (((previousValue != value) 
							|| (this._Area_Conocimiento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Area_Conocimiento.Entity = null;
						previousValue.Pregunta_Abierta.Remove(this);
					}
					this._Area_Conocimiento.Entity = value;
					if ((value != null))
					{
						value.Pregunta_Abierta.Add(this);
						this._Area = value.Id_Area;
					}
					else
					{
						this._Area = default(int);
					}
					this.SendPropertyChanged("Area_Conocimiento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rol")]
	public partial class Rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Rol;
		
		private string _Rol1;
		
		private EntitySet<Aprendiz> _Aprendiz;
		
		private EntitySet<Tutor> _Tutor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_RolChanging(int value);
    partial void OnId_RolChanged();
    partial void OnRol1Changing(string value);
    partial void OnRol1Changed();
    #endregion
		
		public Rol()
		{
			this._Aprendiz = new EntitySet<Aprendiz>(new Action<Aprendiz>(this.attach_Aprendiz), new Action<Aprendiz>(this.detach_Aprendiz));
			this._Tutor = new EntitySet<Tutor>(new Action<Tutor>(this.attach_Tutor), new Action<Tutor>(this.detach_Tutor));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Rol", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Rol
		{
			get
			{
				return this._Id_Rol;
			}
			set
			{
				if ((this._Id_Rol != value))
				{
					this.OnId_RolChanging(value);
					this.SendPropertyChanging();
					this._Id_Rol = value;
					this.SendPropertyChanged("Id_Rol");
					this.OnId_RolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Rol", Storage="_Rol1", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Rol1
		{
			get
			{
				return this._Rol1;
			}
			set
			{
				if ((this._Rol1 != value))
				{
					this.OnRol1Changing(value);
					this.SendPropertyChanging();
					this._Rol1 = value;
					this.SendPropertyChanged("Rol1");
					this.OnRol1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_Aprendiz", Storage="_Aprendiz", ThisKey="Id_Rol", OtherKey="Rol")]
		public EntitySet<Aprendiz> Aprendiz
		{
			get
			{
				return this._Aprendiz;
			}
			set
			{
				this._Aprendiz.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_Tutor", Storage="_Tutor", ThisKey="Id_Rol", OtherKey="Rol")]
		public EntitySet<Tutor> Tutor
		{
			get
			{
				return this._Tutor;
			}
			set
			{
				this._Tutor.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Aprendiz(Aprendiz entity)
		{
			this.SendPropertyChanging();
			entity.Rol1 = this;
		}
		
		private void detach_Aprendiz(Aprendiz entity)
		{
			this.SendPropertyChanging();
			entity.Rol1 = null;
		}
		
		private void attach_Tutor(Tutor entity)
		{
			this.SendPropertyChanging();
			entity.Rol1 = this;
		}
		
		private void detach_Tutor(Tutor entity)
		{
			this.SendPropertyChanging();
			entity.Rol1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sesion")]
	public partial class Sesion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Sesion;
		
		private int _Calificacion;
		
		private int _Estado_Sesion;
		
		private System.DateTime _FechaHoraInicio_Sesion;
		
		private System.DateTime _FechaHoraFin_Sesion;
		
		private EntityRef<Calificacion> _Calificacion1;
		
		private EntityRef<Estado_Sesion> _Estado_Sesion1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_SesionChanging(int value);
    partial void OnId_SesionChanged();
    partial void OnCalificacionChanging(int value);
    partial void OnCalificacionChanged();
    partial void OnEstado_SesionChanging(int value);
    partial void OnEstado_SesionChanged();
    partial void OnFechaHoraInicio_SesionChanging(System.DateTime value);
    partial void OnFechaHoraInicio_SesionChanged();
    partial void OnFechaHoraFin_SesionChanging(System.DateTime value);
    partial void OnFechaHoraFin_SesionChanged();
    #endregion
		
		public Sesion()
		{
			this._Calificacion1 = default(EntityRef<Calificacion>);
			this._Estado_Sesion1 = default(EntityRef<Estado_Sesion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Sesion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Sesion
		{
			get
			{
				return this._Id_Sesion;
			}
			set
			{
				if ((this._Id_Sesion != value))
				{
					this.OnId_SesionChanging(value);
					this.SendPropertyChanging();
					this._Id_Sesion = value;
					this.SendPropertyChanged("Id_Sesion");
					this.OnId_SesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Calificacion", DbType="Int NOT NULL")]
		public int Calificacion
		{
			get
			{
				return this._Calificacion;
			}
			set
			{
				if ((this._Calificacion != value))
				{
					if (this._Calificacion1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCalificacionChanging(value);
					this.SendPropertyChanging();
					this._Calificacion = value;
					this.SendPropertyChanged("Calificacion");
					this.OnCalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_Sesion", DbType="Int NOT NULL")]
		public int Estado_Sesion
		{
			get
			{
				return this._Estado_Sesion;
			}
			set
			{
				if ((this._Estado_Sesion != value))
				{
					if (this._Estado_Sesion1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEstado_SesionChanging(value);
					this.SendPropertyChanging();
					this._Estado_Sesion = value;
					this.SendPropertyChanged("Estado_Sesion");
					this.OnEstado_SesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraInicio_Sesion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaHoraInicio_Sesion
		{
			get
			{
				return this._FechaHoraInicio_Sesion;
			}
			set
			{
				if ((this._FechaHoraInicio_Sesion != value))
				{
					this.OnFechaHoraInicio_SesionChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraInicio_Sesion = value;
					this.SendPropertyChanged("FechaHoraInicio_Sesion");
					this.OnFechaHoraInicio_SesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraFin_Sesion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaHoraFin_Sesion
		{
			get
			{
				return this._FechaHoraFin_Sesion;
			}
			set
			{
				if ((this._FechaHoraFin_Sesion != value))
				{
					this.OnFechaHoraFin_SesionChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraFin_Sesion = value;
					this.SendPropertyChanged("FechaHoraFin_Sesion");
					this.OnFechaHoraFin_SesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Calificacion_Sesion", Storage="_Calificacion1", ThisKey="Calificacion", OtherKey="Id_Calificacion", IsForeignKey=true)]
		public Calificacion Calificacion1
		{
			get
			{
				return this._Calificacion1.Entity;
			}
			set
			{
				Calificacion previousValue = this._Calificacion1.Entity;
				if (((previousValue != value) 
							|| (this._Calificacion1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Calificacion1.Entity = null;
						previousValue.Sesion.Remove(this);
					}
					this._Calificacion1.Entity = value;
					if ((value != null))
					{
						value.Sesion.Add(this);
						this._Calificacion = value.Id_Calificacion;
					}
					else
					{
						this._Calificacion = default(int);
					}
					this.SendPropertyChanged("Calificacion1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Sesion_Sesion", Storage="_Estado_Sesion1", ThisKey="Estado_Sesion", OtherKey="Id_Estado_Sesion", IsForeignKey=true)]
		public Estado_Sesion Estado_Sesion1
		{
			get
			{
				return this._Estado_Sesion1.Entity;
			}
			set
			{
				Estado_Sesion previousValue = this._Estado_Sesion1.Entity;
				if (((previousValue != value) 
							|| (this._Estado_Sesion1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estado_Sesion1.Entity = null;
						previousValue.Sesion.Remove(this);
					}
					this._Estado_Sesion1.Entity = value;
					if ((value != null))
					{
						value.Sesion.Add(this);
						this._Estado_Sesion = value.Id_Estado_Sesion;
					}
					else
					{
						this._Estado_Sesion = default(int);
					}
					this.SendPropertyChanged("Estado_Sesion1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sub_area")]
	public partial class Sub_area : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Sub_Area;
		
		private string _Nombre_Sub;
		
		private int _Area;
		
		private EntityRef<Area_Conocimiento> _Area_Conocimiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_Sub_AreaChanging(int value);
    partial void OnId_Sub_AreaChanged();
    partial void OnNombre_SubChanging(string value);
    partial void OnNombre_SubChanged();
    partial void OnAreaChanging(int value);
    partial void OnAreaChanged();
    #endregion
		
		public Sub_area()
		{
			this._Area_Conocimiento = default(EntityRef<Area_Conocimiento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Sub_Area", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Sub_Area
		{
			get
			{
				return this._Id_Sub_Area;
			}
			set
			{
				if ((this._Id_Sub_Area != value))
				{
					this.OnId_Sub_AreaChanging(value);
					this.SendPropertyChanging();
					this._Id_Sub_Area = value;
					this.SendPropertyChanged("Id_Sub_Area");
					this.OnId_Sub_AreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Sub", DbType="VarChar(30)")]
		public string Nombre_Sub
		{
			get
			{
				return this._Nombre_Sub;
			}
			set
			{
				if ((this._Nombre_Sub != value))
				{
					this.OnNombre_SubChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Sub = value;
					this.SendPropertyChanged("Nombre_Sub");
					this.OnNombre_SubChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="Int NOT NULL")]
		public int Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					if (this._Area_Conocimiento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAreaChanging(value);
					this.SendPropertyChanging();
					this._Area = value;
					this.SendPropertyChanged("Area");
					this.OnAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Area_Conocimiento_Sub_area", Storage="_Area_Conocimiento", ThisKey="Area", OtherKey="Id_Area", IsForeignKey=true)]
		public Area_Conocimiento Area_Conocimiento
		{
			get
			{
				return this._Area_Conocimiento.Entity;
			}
			set
			{
				Area_Conocimiento previousValue = this._Area_Conocimiento.Entity;
				if (((previousValue != value) 
							|| (this._Area_Conocimiento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Area_Conocimiento.Entity = null;
						previousValue.Sub_area.Remove(this);
					}
					this._Area_Conocimiento.Entity = value;
					if ((value != null))
					{
						value.Sub_area.Add(this);
						this._Area = value.Id_Area;
					}
					else
					{
						this._Area = default(int);
					}
					this.SendPropertyChanged("Area_Conocimiento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo_Documento")]
	public partial class Tipo_Documento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Documento;
		
		private string _Nombre_Documento;
		
		private EntitySet<Tutor> _Tutor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_DocumentoChanging(int value);
    partial void OnId_DocumentoChanged();
    partial void OnNombre_DocumentoChanging(string value);
    partial void OnNombre_DocumentoChanged();
    #endregion
		
		public Tipo_Documento()
		{
			this._Tutor = new EntitySet<Tutor>(new Action<Tutor>(this.attach_Tutor), new Action<Tutor>(this.detach_Tutor));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Documento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Documento
		{
			get
			{
				return this._Id_Documento;
			}
			set
			{
				if ((this._Id_Documento != value))
				{
					this.OnId_DocumentoChanging(value);
					this.SendPropertyChanging();
					this._Id_Documento = value;
					this.SendPropertyChanged("Id_Documento");
					this.OnId_DocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Documento", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre_Documento
		{
			get
			{
				return this._Nombre_Documento;
			}
			set
			{
				if ((this._Nombre_Documento != value))
				{
					this.OnNombre_DocumentoChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Documento = value;
					this.SendPropertyChanged("Nombre_Documento");
					this.OnNombre_DocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_Documento_Tutor", Storage="_Tutor", ThisKey="Id_Documento", OtherKey="Tipo_Documento")]
		public EntitySet<Tutor> Tutor
		{
			get
			{
				return this._Tutor;
			}
			set
			{
				this._Tutor.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tutor(Tutor entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_Documento1 = this;
		}
		
		private void detach_Tutor(Tutor entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_Documento1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Titulo_Obtenido")]
	public partial class Titulo_Obtenido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Titulo;
		
		private string _Nombre_Titulo;
		
		private EntitySet<Nivel_Estudio> _Nivel_Estudio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_TituloChanging(int value);
    partial void OnId_TituloChanged();
    partial void OnNombre_TituloChanging(string value);
    partial void OnNombre_TituloChanged();
    #endregion
		
		public Titulo_Obtenido()
		{
			this._Nivel_Estudio = new EntitySet<Nivel_Estudio>(new Action<Nivel_Estudio>(this.attach_Nivel_Estudio), new Action<Nivel_Estudio>(this.detach_Nivel_Estudio));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Titulo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Titulo
		{
			get
			{
				return this._Id_Titulo;
			}
			set
			{
				if ((this._Id_Titulo != value))
				{
					this.OnId_TituloChanging(value);
					this.SendPropertyChanging();
					this._Id_Titulo = value;
					this.SendPropertyChanged("Id_Titulo");
					this.OnId_TituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Titulo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre_Titulo
		{
			get
			{
				return this._Nombre_Titulo;
			}
			set
			{
				if ((this._Nombre_Titulo != value))
				{
					this.OnNombre_TituloChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Titulo = value;
					this.SendPropertyChanged("Nombre_Titulo");
					this.OnNombre_TituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Titulo_Obtenido_Nivel_Estudio", Storage="_Nivel_Estudio", ThisKey="Id_Titulo", OtherKey="Titulo_Obtenido")]
		public EntitySet<Nivel_Estudio> Nivel_Estudio
		{
			get
			{
				return this._Nivel_Estudio;
			}
			set
			{
				this._Nivel_Estudio.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Nivel_Estudio(Nivel_Estudio entity)
		{
			this.SendPropertyChanging();
			entity.Titulo_Obtenido1 = this;
		}
		
		private void detach_Nivel_Estudio(Nivel_Estudio entity)
		{
			this.SendPropertyChanging();
			entity.Titulo_Obtenido1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tutor")]
	public partial class Tutor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Tutor;
		
		private int _Tipo_Documento;
		
		private int _Numero_Documento;
		
		private int _Experiencia;
		
		private string _Nombres_Tutor;
		
		private string _Apellidos_Tutor;
		
		private string _Correo_Electronico_tutor;
		
		private string _Clave_Tutor;
		
		private string _Telefono_Tutor;
		
		private int _Nivel_Estudio;
		
		private string _Tiempo_Laborado;
		
		private System.Nullable<int> _Estado;
		
		private int _Rol;
		
		private int _Area_Conocimiento;
		
		private string _DescripcionPerfil;
		
		private EntitySet<Estado_Sesion> _Estado_Sesion;
		
		private EntityRef<Area_Conocimiento> _Area_Conocimiento1;
		
		private EntityRef<Estados> _Estados;
		
		private EntityRef<Experiencia> _Experiencia1;
		
		private EntityRef<Rol> _Rol1;
		
		private EntityRef<Tipo_Documento> _Tipo_Documento1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_TutorChanging(int value);
    partial void OnId_TutorChanged();
    partial void OnTipo_DocumentoChanging(int value);
    partial void OnTipo_DocumentoChanged();
    partial void OnNumero_DocumentoChanging(int value);
    partial void OnNumero_DocumentoChanged();
    partial void OnExperienciaChanging(int value);
    partial void OnExperienciaChanged();
    partial void OnNombres_TutorChanging(string value);
    partial void OnNombres_TutorChanged();
    partial void OnApellidos_TutorChanging(string value);
    partial void OnApellidos_TutorChanged();
    partial void OnCorreo_Electronico_tutorChanging(string value);
    partial void OnCorreo_Electronico_tutorChanged();
    partial void OnClave_TutorChanging(string value);
    partial void OnClave_TutorChanged();
    partial void OnTelefono_TutorChanging(string value);
    partial void OnTelefono_TutorChanged();
    partial void OnNivel_EstudioChanging(int value);
    partial void OnNivel_EstudioChanged();
    partial void OnTiempo_LaboradoChanging(string value);
    partial void OnTiempo_LaboradoChanged();
    partial void OnEstadoChanging(System.Nullable<int> value);
    partial void OnEstadoChanged();
    partial void OnRolChanging(int value);
    partial void OnRolChanged();
    partial void OnArea_ConocimientoChanging(int value);
    partial void OnArea_ConocimientoChanged();
    partial void OnDescripcionPerfilChanging(string value);
    partial void OnDescripcionPerfilChanged();
    #endregion
		
		public Tutor()
		{
			this._Estado_Sesion = new EntitySet<Estado_Sesion>(new Action<Estado_Sesion>(this.attach_Estado_Sesion), new Action<Estado_Sesion>(this.detach_Estado_Sesion));
			this._Area_Conocimiento1 = default(EntityRef<Area_Conocimiento>);
			this._Estados = default(EntityRef<Estados>);
			this._Experiencia1 = default(EntityRef<Experiencia>);
			this._Rol1 = default(EntityRef<Rol>);
			this._Tipo_Documento1 = default(EntityRef<Tipo_Documento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Tutor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Tutor
		{
			get
			{
				return this._Id_Tutor;
			}
			set
			{
				if ((this._Id_Tutor != value))
				{
					this.OnId_TutorChanging(value);
					this.SendPropertyChanging();
					this._Id_Tutor = value;
					this.SendPropertyChanged("Id_Tutor");
					this.OnId_TutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo_Documento", DbType="Int NOT NULL")]
		public int Tipo_Documento
		{
			get
			{
				return this._Tipo_Documento;
			}
			set
			{
				if ((this._Tipo_Documento != value))
				{
					if (this._Tipo_Documento1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTipo_DocumentoChanging(value);
					this.SendPropertyChanging();
					this._Tipo_Documento = value;
					this.SendPropertyChanged("Tipo_Documento");
					this.OnTipo_DocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero_Documento", DbType="Int NOT NULL")]
		public int Numero_Documento
		{
			get
			{
				return this._Numero_Documento;
			}
			set
			{
				if ((this._Numero_Documento != value))
				{
					this.OnNumero_DocumentoChanging(value);
					this.SendPropertyChanging();
					this._Numero_Documento = value;
					this.SendPropertyChanged("Numero_Documento");
					this.OnNumero_DocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Experiencia", DbType="Int NOT NULL")]
		public int Experiencia
		{
			get
			{
				return this._Experiencia;
			}
			set
			{
				if ((this._Experiencia != value))
				{
					if (this._Experiencia1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnExperienciaChanging(value);
					this.SendPropertyChanging();
					this._Experiencia = value;
					this.SendPropertyChanged("Experiencia");
					this.OnExperienciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres_Tutor", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombres_Tutor
		{
			get
			{
				return this._Nombres_Tutor;
			}
			set
			{
				if ((this._Nombres_Tutor != value))
				{
					this.OnNombres_TutorChanging(value);
					this.SendPropertyChanging();
					this._Nombres_Tutor = value;
					this.SendPropertyChanged("Nombres_Tutor");
					this.OnNombres_TutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos_Tutor", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Apellidos_Tutor
		{
			get
			{
				return this._Apellidos_Tutor;
			}
			set
			{
				if ((this._Apellidos_Tutor != value))
				{
					this.OnApellidos_TutorChanging(value);
					this.SendPropertyChanging();
					this._Apellidos_Tutor = value;
					this.SendPropertyChanged("Apellidos_Tutor");
					this.OnApellidos_TutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo_Electronico_tutor", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Correo_Electronico_tutor
		{
			get
			{
				return this._Correo_Electronico_tutor;
			}
			set
			{
				if ((this._Correo_Electronico_tutor != value))
				{
					this.OnCorreo_Electronico_tutorChanging(value);
					this.SendPropertyChanging();
					this._Correo_Electronico_tutor = value;
					this.SendPropertyChanged("Correo_Electronico_tutor");
					this.OnCorreo_Electronico_tutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave_Tutor", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Clave_Tutor
		{
			get
			{
				return this._Clave_Tutor;
			}
			set
			{
				if ((this._Clave_Tutor != value))
				{
					this.OnClave_TutorChanging(value);
					this.SendPropertyChanging();
					this._Clave_Tutor = value;
					this.SendPropertyChanged("Clave_Tutor");
					this.OnClave_TutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono_Tutor", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Telefono_Tutor
		{
			get
			{
				return this._Telefono_Tutor;
			}
			set
			{
				if ((this._Telefono_Tutor != value))
				{
					this.OnTelefono_TutorChanging(value);
					this.SendPropertyChanging();
					this._Telefono_Tutor = value;
					this.SendPropertyChanged("Telefono_Tutor");
					this.OnTelefono_TutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel_Estudio", DbType="Int NOT NULL")]
		public int Nivel_Estudio
		{
			get
			{
				return this._Nivel_Estudio;
			}
			set
			{
				if ((this._Nivel_Estudio != value))
				{
					this.OnNivel_EstudioChanging(value);
					this.SendPropertyChanging();
					this._Nivel_Estudio = value;
					this.SendPropertyChanged("Nivel_Estudio");
					this.OnNivel_EstudioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tiempo_Laborado", DbType="VarChar(10)")]
		public string Tiempo_Laborado
		{
			get
			{
				return this._Tiempo_Laborado;
			}
			set
			{
				if ((this._Tiempo_Laborado != value))
				{
					this.OnTiempo_LaboradoChanging(value);
					this.SendPropertyChanging();
					this._Tiempo_Laborado = value;
					this.SendPropertyChanged("Tiempo_Laborado");
					this.OnTiempo_LaboradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int")]
		public System.Nullable<int> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					if (this._Estados.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="Int NOT NULL")]
		public int Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					if (this._Rol1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRolChanging(value);
					this.SendPropertyChanging();
					this._Rol = value;
					this.SendPropertyChanged("Rol");
					this.OnRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area_Conocimiento", DbType="Int NOT NULL")]
		public int Area_Conocimiento
		{
			get
			{
				return this._Area_Conocimiento;
			}
			set
			{
				if ((this._Area_Conocimiento != value))
				{
					if (this._Area_Conocimiento1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnArea_ConocimientoChanging(value);
					this.SendPropertyChanging();
					this._Area_Conocimiento = value;
					this.SendPropertyChanged("Area_Conocimiento");
					this.OnArea_ConocimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionPerfil", DbType="VarChar(400) NOT NULL", CanBeNull=false)]
		public string DescripcionPerfil
		{
			get
			{
				return this._DescripcionPerfil;
			}
			set
			{
				if ((this._DescripcionPerfil != value))
				{
					this.OnDescripcionPerfilChanging(value);
					this.SendPropertyChanging();
					this._DescripcionPerfil = value;
					this.SendPropertyChanged("DescripcionPerfil");
					this.OnDescripcionPerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tutor_Estado_Sesion", Storage="_Estado_Sesion", ThisKey="Id_Tutor", OtherKey="Tutor")]
		public EntitySet<Estado_Sesion> Estado_Sesion
		{
			get
			{
				return this._Estado_Sesion;
			}
			set
			{
				this._Estado_Sesion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Area_Conocimiento_Tutor", Storage="_Area_Conocimiento1", ThisKey="Area_Conocimiento", OtherKey="Id_Area", IsForeignKey=true)]
		public Area_Conocimiento Area_Conocimiento1
		{
			get
			{
				return this._Area_Conocimiento1.Entity;
			}
			set
			{
				Area_Conocimiento previousValue = this._Area_Conocimiento1.Entity;
				if (((previousValue != value) 
							|| (this._Area_Conocimiento1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Area_Conocimiento1.Entity = null;
						previousValue.Tutor.Remove(this);
					}
					this._Area_Conocimiento1.Entity = value;
					if ((value != null))
					{
						value.Tutor.Add(this);
						this._Area_Conocimiento = value.Id_Area;
					}
					else
					{
						this._Area_Conocimiento = default(int);
					}
					this.SendPropertyChanged("Area_Conocimiento1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estados_Tutor", Storage="_Estados", ThisKey="Estado", OtherKey="Id_sesion_tutor", IsForeignKey=true)]
		public Estados Estados
		{
			get
			{
				return this._Estados.Entity;
			}
			set
			{
				Estados previousValue = this._Estados.Entity;
				if (((previousValue != value) 
							|| (this._Estados.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estados.Entity = null;
						previousValue.Tutor.Remove(this);
					}
					this._Estados.Entity = value;
					if ((value != null))
					{
						value.Tutor.Add(this);
						this._Estado = value.Id_sesion_tutor;
					}
					else
					{
						this._Estado = default(Nullable<int>);
					}
					this.SendPropertyChanged("Estados");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Experiencia_Tutor", Storage="_Experiencia1", ThisKey="Experiencia", OtherKey="Id_Experiencia", IsForeignKey=true)]
		public Experiencia Experiencia1
		{
			get
			{
				return this._Experiencia1.Entity;
			}
			set
			{
				Experiencia previousValue = this._Experiencia1.Entity;
				if (((previousValue != value) 
							|| (this._Experiencia1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Experiencia1.Entity = null;
						previousValue.Tutor.Remove(this);
					}
					this._Experiencia1.Entity = value;
					if ((value != null))
					{
						value.Tutor.Add(this);
						this._Experiencia = value.Id_Experiencia;
					}
					else
					{
						this._Experiencia = default(int);
					}
					this.SendPropertyChanged("Experiencia1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_Tutor", Storage="_Rol1", ThisKey="Rol", OtherKey="Id_Rol", IsForeignKey=true)]
		public Rol Rol1
		{
			get
			{
				return this._Rol1.Entity;
			}
			set
			{
				Rol previousValue = this._Rol1.Entity;
				if (((previousValue != value) 
							|| (this._Rol1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rol1.Entity = null;
						previousValue.Tutor.Remove(this);
					}
					this._Rol1.Entity = value;
					if ((value != null))
					{
						value.Tutor.Add(this);
						this._Rol = value.Id_Rol;
					}
					else
					{
						this._Rol = default(int);
					}
					this.SendPropertyChanged("Rol1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_Documento_Tutor", Storage="_Tipo_Documento1", ThisKey="Tipo_Documento", OtherKey="Id_Documento", IsForeignKey=true)]
		public Tipo_Documento Tipo_Documento1
		{
			get
			{
				return this._Tipo_Documento1.Entity;
			}
			set
			{
				Tipo_Documento previousValue = this._Tipo_Documento1.Entity;
				if (((previousValue != value) 
							|| (this._Tipo_Documento1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tipo_Documento1.Entity = null;
						previousValue.Tutor.Remove(this);
					}
					this._Tipo_Documento1.Entity = value;
					if ((value != null))
					{
						value.Tutor.Add(this);
						this._Tipo_Documento = value.Id_Documento;
					}
					else
					{
						this._Tipo_Documento = default(int);
					}
					this.SendPropertyChanged("Tipo_Documento1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Estado_Sesion(Estado_Sesion entity)
		{
			this.SendPropertyChanging();
			entity.Tutor1 = this;
		}
		
		private void detach_Estado_Sesion(Estado_Sesion entity)
		{
			this.SendPropertyChanging();
			entity.Tutor1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tutor_Has_Area_Conocimiento")]
	public partial class Tutor_Has_Area_Conocimiento
	{
		
		private int _Tutor;
		
		private int _Area_Conocimiento;
		
		public Tutor_Has_Area_Conocimiento()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutor", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Tutor
		{
			get
			{
				return this._Tutor;
			}
			set
			{
				if ((this._Tutor != value))
				{
					this._Tutor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area_Conocimiento", DbType="Int NOT NULL")]
		public int Area_Conocimiento
		{
			get
			{
				return this._Area_Conocimiento;
			}
			set
			{
				if ((this._Area_Conocimiento != value))
				{
					this._Area_Conocimiento = value;
				}
			}
		}
	}
	
	public partial class tutodisponible3Result
	{
		
		private int _Id_Tutor;
		
		private string _Nombres_Tutor;
		
		private string _Apellidos_Tutor;
		
		private int _Nivel_Estudio;
		
		private string _DescripcionPerfil;
		
		public tutodisponible3Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Tutor", DbType="Int NOT NULL")]
		public int Id_Tutor
		{
			get
			{
				return this._Id_Tutor;
			}
			set
			{
				if ((this._Id_Tutor != value))
				{
					this._Id_Tutor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres_Tutor", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombres_Tutor
		{
			get
			{
				return this._Nombres_Tutor;
			}
			set
			{
				if ((this._Nombres_Tutor != value))
				{
					this._Nombres_Tutor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos_Tutor", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Apellidos_Tutor
		{
			get
			{
				return this._Apellidos_Tutor;
			}
			set
			{
				if ((this._Apellidos_Tutor != value))
				{
					this._Apellidos_Tutor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel_Estudio", DbType="Int NOT NULL")]
		public int Nivel_Estudio
		{
			get
			{
				return this._Nivel_Estudio;
			}
			set
			{
				if ((this._Nivel_Estudio != value))
				{
					this._Nivel_Estudio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionPerfil", DbType="VarChar(400) NOT NULL", CanBeNull=false)]
		public string DescripcionPerfil
		{
			get
			{
				return this._DescripcionPerfil;
			}
			set
			{
				if ((this._DescripcionPerfil != value))
				{
					this._DescripcionPerfil = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
